name: test test

on:
  workflow_call:
    inputs:
      test_suite:
        description: 'The test suite to run'
        required: true
        type: string

jobs:
  execute_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Execute tests
        run: vendor/bin/phpunit --testsuite ${{ inputs.test_suite }}
        env:
          DB_PORT: 3306
          DB_USERNAME: root
          AWS_ACCESS_KEY_ID: random_key
          AWS_SECRET_ACCESS_KEY: random_secret
