name: PHPCS check

on: pull_request

jobs:
  phpcs:
    name: PHP checks
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: cs2pr, phpcs

      - name: Run phpcs
        run: phpcs -q --report=checkstyle src | cs2pr
