name: tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    services:
      memcached:
        image: memcached:1.6-alpine
        ports:
          - 11211:11211
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: forge
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: true
      matrix:
        tests:
          - 'Auth'
          - 'Broadcasting'
#          - 'Bus'
#          - 'Cache'
#          - 'Conditionable'
#          - 'Config'
#          - 'Console'
#          - 'Container'
#          - 'Cookie'
#          - 'Database'
#          - 'Encryption'
#          - 'Events'
#          - 'Filesystem'
#          - 'Foundation'
#          - 'Hashing'
#          - 'Http'
#          - 'Log'
#          - 'Mail'
#          - 'Notifications'
#          - 'Pagination'
#          - 'Pipeline'
#          - 'Queue'
#          - 'Redis'
#          - 'Session'
#          - 'Support'
#          - 'Testing'
#          - 'Translation'
#          - 'Validation'
#          - 'View'

    name: PHP - ${{ matrix.tests }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis-phpredis/phpredis@5.3.7, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis --enable-redis-igbinary --enable-redis-msgpack --enable-redis-lzf --with-liblzf --enable-redis-zstd --with-libzstd --enable-redis-lz4 --with-liblz4
          REDIS_LIBS: liblz4-dev, liblzf-dev, libzstd-dev

      - name: Install Dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

  tests-job:
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      test_suite: ${{ matrix.tests }}
